# Generated by Django 5.0.1 on 2024-02-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='last_name',
        ),
    ]
