# Generated by Django 5.0.1 on 2024-02-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_first_name_admin_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bmr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
